---
title: "Visualisation"
output: html_document
date: "2023-11-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


devtools::load_all()

```

```{r}
fcst_all <- readr::read_csv("output/iron ore/20231216tgt_irn_fcst_all.csv", show_col_types = F) %>%
  setnames(., old = "...1", new = "idx") %>%
  data.table()

fcst_all_piv <-
  fcst_all %>%
  dcast(., dte ~ step, value.var = "y_pred")

datr <- readr::read_csv("data/dat_raw.csv", show_col_types = F) %>%
  data.table()

datft <- readr::read_csv("data/dat_ft.csv", show_col_types = F) %>%
  data.table()

mod_rem <- unique(fcst_all$model_name)[!unique(fcst_all$model_name) %in% 
                                         c("arima_sea", "combined", "reg", "gru_grusubset", "esrnn_ftsubset",
                                           "rnn_rnnsubset", "arima_xreg")] 

vis <-
  rbind(
  datr[, .(Date = dte, Price = tgt_crd, model_name = "target", step = 0)],
  fcst_all[, .(Date = dte, Price = y_pred, model_name, step = step + 1)]) %>%
  .[Date > "2022-09-01"] #%>%
  #.[!model_name %chin% mod_rem] %>%
  #.[, mod_step := paste(model_name, step, sep = "_")]



# vis <- merge(datr[, .(dte, val = tgt_crd)], 
#              fcst_all[, .(dte, y_pred, model_name, step = step + 1)], 
#               by = "dte", all.x = T) %>%
#   .[!model_name %chin% mod_rem] %>%
#   .[dte >= "2021-01-01"] %>%
#   .[, mod_step := paste(model_name, step, sep = "_")]

```


## Forecast Visuals

### Together

```{r, fig.height=5, fig.width=8}

plot_list <- list()

model_names <- data.table(model_name_tech = c("arima_xreg", "combined", "reg", "rnn_rnnsubset", "esrnn_ftsubset","arima_sea"),
                  model_name_pretty = c("ARIMA Regressed", "Combined", "OLS", "RNN", "ESRNN", "ARIMA Seasonality"))

for (mod in model_names$model_name_tech) {
  
  p <- 
    vis %>%
    .[model_name %chin% c(mod, "target")] %>% 
    ggplot() +
    geom_line(aes(Date, Price, color = factor(step)), size = 1) +
    theme_minimal() +
    scale_color_brewer(palette = "Dark2") +
    theme(legend.position = "none", axis.title.x=element_blank()) +
    labs(title = model_names[model_name_tech == mod, model_name_pretty]
         )
  
  plot_list[[mod]] <- p
  
}

(plot_list[["Arima_Best"]] | plot_list[["combined"]]) / (plot_list[["reg"]] | plot_list[["rnn_rnnsubset"]]) / plot_list[["esrnn_ftsubset"]]

```

### Features

```{r}

pred_files <- list.files("data") %>%
  .[stringr::str_detect(., "pred")] %>%
  .[!stringr::str_detect(., "hyper")]

pred_data_list <- list()

pred_data <- vector()

for (i in 1:length(pred_files)) {
  
  pf = pred_files[i]
  
  pred_data_list[[i]] <- names(readr::read_csv(paste0("data/", pf), show_col_types = F))
  
  pred_data <- c(pred_data, names(readr::read_csv(paste0("data/", pf), show_col_types = F))) 
  
}


pred_cols <- data.table(pred = pred_data) %>%
  .[, .N, by = "pred"] %>%
  .[order(-N)]


readr::write_csv(pred_cols, "Writeup/Images/pred_cols.csv")
# pred_cols <- rbind(pred_data_list)

```


### Facet

```{r}

vis_facet <-
  vis %>%
  dcast(., dte ~ step, value.var = "val") %>%
  melt(., id.vars = c("dte", "0"))

ggplot(vis_facet) +
  geom_line(aes(dte, value), size = 1, color = "red") +
  geom_line(aes(dte, `0`), size = 1, colour = "blue") +
  facet_wrap(vars(variable))



```

## Seasonality

### Single

```{r, fig.width=8, fig.height=6}

#Seasonality
inds <- seq(min(datr[, dte]), max(datr[, dte]), by = "day")

crd_ts <- ts(datr[, tgt_crd],start = c(year(min(inds)), as.numeric(format(inds[1], "%j"))), frequency = 365)
irn_ts <- ts(datr[, tgt_irn],start = c(year(min(inds)), as.numeric(format(inds[1], "%j"))), frequency = 365)

crd_ts_mth <- ts(datr[, .(tgt_crd = mean(tgt_crd)), by = floor_date(dte, "month")][["tgt_crd"]],
                 start = c(year(min(inds)), month(min(inds))), frequency = 12)

irn_ts_mth <- ts(datr[, .(tgt_irn = mean(tgt_irn)), by = floor_date(dte, "month")][["tgt_irn"]],
                 start = c(year(min(inds)), month(min(inds))), frequency = 12)

decomp7 <- stl(crd_ts, s.window = "periodic", t.window = 7)
decomp31 <- stl(crd_ts, s.window = "periodic", t.window = 31)
decomp_mth <- stl(crd_ts_mth, s.window = "periodic", t.window = 12)

forecast::autoplot(decomp7) / forecast::autoplot(decomp31)

```

### Multiple

```{r crude_multiple_seas, fig.width=12, fig.height=8}

forecast::msts(datr[, tgt_crd], seasonal.periods = c(7, 365, 28, 90),
               start = c(year(min(inds)), as.numeric(format(inds[1], "%j")))) %>%
  forecast::mstl() %>%
  forecast::autoplot() 

```


```{r irn_multiple_seas, fig.width=12, fig.height=8}

irn_msts <- 
forecast::msts(datr[, tgt_irn], seasonal.periods = c(7, 365, 28, 90), ts.frequency = 365,
               start = c(year(min(inds)), as.numeric(format(inds[1], "%j")))) %>%
forecast::mstl() 
  
forecast::autoplot(irn_msts) +
  scale_x_continuous(limits = c(2016,2019))

```

### Seasonality Tests

```{r}
print("Crude7")
summary(seastests::combined_test(crd_ts, freq = 7))
print("Crude28")
summary(seastests::combined_test(crd_ts, freq = 28))
print("Crude90")
summary(seastests::combined_test(crd_ts, freq = 90))
print("Crude365")
summary(seastests::combined_test(irn_ts, freq = 365))

print("Iron7")
summary(seastests::combined_test(irn_ts, freq = 7))
print("Iron28")
summary(seastests::combined_test(irn_ts, freq = 28))
print("Iron90")
summary(seastests::combined_test(irn_ts, freq = 90))
print("Iron365")
summary(seastests::combined_test(irn_ts, freq = 365))


```

## Feature Correlation

### Raw

```{r, fig.height=10, fig.width=8}



cor_r <- 
  datr %>%
  copy() %>%
  setnames(old = "tgt_crd", new = "tgt_crd01") %>%
  setnames(old = "tgt_irn", new = "tgt_irn01") %>%
  .[,tgt_crd16 := shift(close_crd, 16)] %>%
  .[,tgt_crd32 := shift(close_crd, 32)] %>%
  .[,tgt_crd49 := shift(close_crd, 49)] %>%
  .[,tgt_irn16 := shift(close_irn, 16)] %>%
  .[,tgt_irn32 := shift(close_irn, 32)] %>%
  .[,tgt_irn49 := shift(close_irn, 49)] %>%
  na.omit()
  
tgts <- c("tgt_crd01", "tgt_crd16", "tgt_crd32", "tgt_crd49", "tgt_irn01", "tgt_irn16", "tgt_irn32", "tgt_irn49")
  
cor_r_tgt <- data.table()

#tgt = tgts[1]
for (tgt in tgts) {
  
  tgts_remove <- c(tgts, "dte") #[!tgts %in% tgt]
  
  tgt_cor <- cor(cor_r[, !..tgts_remove], cor_r[, get(tgt)])
  
  if (ncol(cor_r_tgt) == 0) {
    
    cor_r_tgt <- cbind(cor_r_tgt, data.table(Feature = rownames(tgt_cor), target = tgt_cor[,1])) %>%
      setnames(old = "target", new = tgt)
    
  } else {
    
    cor_r_tgt <- cbind(cor_r_tgt, data.table(target = tgt_cor[,1])) %>%
      setnames(old = "target", new = tgt)
    
  }
  
}


cor_r_tgt_lng <- 
  cor_r_tgt %>%
  melt(id.vars = "Feature", variable.name = "target", value.name = "corr", variable.factor = F) %>%
  .[, commodity := ifelse(grepl("crd", target), "Crude", "Iron Ore")] %>%
  .[, tgt_generic := paste0("tgt",stringr::str_sub(target, -2))] %>%
  .[, corr := round(corr, 2)] %>%
  .[, corr_abs := abs(corr)]

crd_cor_r_tgt_lng <- 
  cor_r_tgt_lng %>%
  .[!grepl("irn", Feature) & commodity == "Crude"]

crd_cor_r_tgt_top <- crd_cor_r_tgt_lng[, .(corr_abs = mean(corr_abs)), by = "Feature"][order(corr_abs)]

p1 <- 
ggplot(crd_cor_r_tgt_lng) +
  geom_tile(aes(tgt_generic, factor(Feature, levels = crd_cor_r_tgt_top$Feature), fill = corr_abs)) +
  facet_wrap(vars(commodity)) +
  scale_fill_gradient(low = "white", high = "#b30000") +
  geom_text(aes(tgt_generic, Feature, label = corr), color = "black", size = 2) +
  theme(axis.text.y=element_text(size=7), axis.title.x=element_blank(), legend.position = "none") +
  ylab("Feature")


irn_cor_r_tgt_lng <- 
  cor_r_tgt_lng %>%
  .[!grepl("crd", Feature) & commodity == "Iron Ore"]

irn_cor_r_tgt_top <- irn_cor_r_tgt_lng[, .(corr_abs = mean(corr_abs)), by = "Feature"][order(corr_abs)]

p2 <- 
ggplot(irn_cor_r_tgt_lng) +
  geom_tile(aes(tgt_generic, factor(Feature, levels = irn_cor_r_tgt_top$Feature), fill = corr_abs)) +
  facet_wrap(vars(commodity)) +
  scale_fill_gradient(low = "white", high = "#8c0101") +
  geom_text(aes(tgt_generic, Feature, label = corr), color = "black", size = 2) +
  theme(axis.text.y=element_text(size=7), axis.title.x=element_blank(), axis.title.y=element_blank()) 

p1 |  p2

#TODO: add categories for the differnt features

```


```{r, fig.height=8, fig.width=8}

cor_ft <- 
  datft %>%
  copy() %>%
  setnames(old = "tgt_crd", new = "tgt_crd01") %>%
  setnames(old = "tgt_irn", new = "tgt_irn01") %>%
  .[,tgt_crd16 := shift(close_crd, 16)] %>%
  .[,tgt_crd32 := shift(close_crd, 32)] %>%
  .[,tgt_crd49 := shift(close_crd, 49)] %>%
  .[,tgt_irn16 := shift(close_irn, 16)] %>%
  .[,tgt_irn32 := shift(close_irn, 32)] %>%
  .[,tgt_irn49 := shift(close_irn, 49)] %>%
  na.omit()
  
tgts <- c("tgt_crd01", "tgt_crd16", "tgt_crd32", "tgt_crd49", "tgt_irn01", "tgt_irn16", "tgt_irn32", "tgt_irn49")
  
cor_ft_tgt <- data.table()

#tgt = tgts[1]
for (tgt in tgts) {
  
  tgts_remove <- c(tgts, "dte") #[!tgts %in% tgt]
  
  tgt_cor <- cor(cor_ft[, !..tgts_remove], cor_ft[, get(tgt)])
  
  if (ncol(cor_ft_tgt) == 0) {
    
    cor_ft_tgt <- cbind(cor_ft_tgt, data.table(Feature = rownames(tgt_cor), target = tgt_cor[,1])) %>%
      setnames(old = "target", new = tgt)
    
  } else {
    
    cor_ft_tgt <- cbind(cor_ft_tgt, data.table(target = tgt_cor[,1])) %>%
      setnames(old = "target", new = tgt)
    
  }
  
}


cor_ft_tgt_lng <- 
  cor_ft_tgt %>%
  melt(id.vars = "Feature", variable.name = "target", value.name = "corr", variable.factor = F) %>%
  .[, commodity := ifelse(grepl("crd", target), "Crude", "Iron Ore")] %>%
  .[, tgt_generic := paste0("tgt",stringr::str_sub(target, -2))] %>%
  .[, corr := round(corr, 2)] %>%
  .[, corr_abs := abs(corr)]

crd_cor_ft_tgt_lng <- 
  cor_ft_tgt_lng %>%
  .[!grepl("irn", Feature) & commodity == "Crude"]

crd_cor_ft_tgt_top <- crd_cor_ft_tgt_lng[, .(corr_abs = mean(corr_abs)), by = "Feature"][order(corr_abs)]  %>%
  .[corr_abs > 0.6]


p1 <- 
ggplot(crd_cor_ft_tgt_lng[Feature %chin% crd_cor_ft_tgt_top[, Feature]]) +
  geom_tile(aes(tgt_generic, factor(Feature, levels = crd_cor_ft_tgt_top$Feature), fill = corr_abs)) +
  facet_wrap(vars(commodity)) +
  scale_fill_gradient(low = "white", high = "#b30000") +
  geom_text(aes(tgt_generic, Feature, label = corr), color = "black", size = 2) +
  theme(axis.text.y=element_text(size=7), axis.title.x=element_blank(), legend.position = "none") +
  ylab("Feature")


irn_cor_ft_tgt_lng <- 
  cor_ft_tgt_lng %>%
  .[!grepl("crd", Feature) & commodity == "Iron Ore"]

irn_cor_ft_tgt_top <- irn_cor_ft_tgt_lng[, .(corr_abs = mean(corr_abs)), by = "Feature"][order(corr_abs)]  %>%
  .[corr_abs > 0.6]


p2 <- 
ggplot(irn_cor_ft_tgt_lng[Feature %chin% irn_cor_ft_tgt_top[, Feature]]) +
  geom_tile(aes(tgt_generic, factor(Feature, levels = irn_cor_ft_tgt_top$Feature), fill = corr_abs)) +
  facet_wrap(vars(commodity)) +
  scale_fill_gradient(low = "white", high = "#b30000") +
  geom_text(aes(tgt_generic, Feature, label = corr), color = "black", size = 2) +
  theme(axis.text.y=element_text(size=7), axis.title.x=element_blank(), axis.title.y=element_blank()) 

p1 |  p2

```

```{r}

#### Correlated Values and filter to only the most correlated values ####

# crd_cor <- cor(datft[, !c("tgt_crd", "dte")], datft[, tgt_crd])
# 
# crd_cols <- data.table(cols = rownames(crd_cor), vals = abs(crd_cor[,1]))
# 
# irn_cor <- cor(dat_synth_ft[, !c("tgt_irn", "dte")], dat_synth_ft[, tgt_irn])
# 
# irn_cols <- data.table(cols = rownames(irn_cor), vals = abs(irn_cor[,1]))
# 
# cols <- unique(c("dte", "tgt_crd", "tgt_irn", irn_cols[vals > 0.4, cols], crd_cols[vals > 0.4, cols]))
# 
# cor_dt <- data.table(crd_names = names(crd_cor)), crd_corr = crd_cor,
#                       crd_names = names(crd_cor)), crd_corr = crd_cor

```

